version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: athlete-performance-db
    environment:
      POSTGRES_DB: athlete_performance
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - athlete-performance-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: athlete-performance-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: athlete_performance
      DB_USERNAME: postgres
      DB_PASSWORD: password
      JWT_SECRET: mySecretKey123456789012345678901234567890
      JWT_EXPIRATION: 86400000
      JWT_REFRESH_EXPIRATION: 604800000
      DDL_AUTO: update
      SHOW_SQL: false
      LOG_LEVEL: INFO
    ports:
      - "9080:9090"
    networks:
      - athlete-performance-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:

networks:
  athlete-performance-network:
    driver: bridge