spring:
  application:
    name: mtor-evolution

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mtor_evolution}
    username: ${SPRING_DATASOURCE_USERNAME:mtor_user}
    password: ${SPRING_DATASOURCE_PASSWORD:mtor_pass}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080

app:
  jwt:
    secret: ${JWT_SECRET:mySecretKeyMtorEvolution2024}
    expiration: 86400000 # 24 hours
    refresh-expiration: 2592000000 # 30 days

logging:
  level:
    com.mtor.evolution: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method